### ISSUE TITLE
SSL Self Signed Verification

### ISSUE THREAD

**Issue by tfox72** [microsoft/powerbi-jupyter#13]
Love that your creating this!!

Was working my way through the Quick Start in the documentation and made it to the # Use auth object. That is where it failed, not an SSL expert so was hoping you could help. Below is the error that I get whether using the device_auth or user_token.

Any Suggestions?

![image](https://user-images.githubusercontent.com/14864902/119900988-26fabc80-befa-11eb-80d8-c4c02dc25d96.png)

**Comment by orshemesh16** [comment]
Hi, new version has been released recently (2.0.1) with several breaking changes in the authentication methods that simplify the API. You can see full documentation [here](https://github.com/microsoft/powerbi-jupyter/blob/main/DOCUMENTATION.md). If you still encounter authentication issues, please open new issue.
