### ISSUE TITLE
Documentation and notebook links are broken

### ISSUE THREAD

**Issue by pawarbi** [microsoft/powerbi-jupyter#15]
The link to "Documentation" and "Demo Notebook" are broken on this page: https://github.com/microsoft/powerbi-jupyter/

The Documentation link points to : https://github.com/microsoft/powerbi-jupyter/blob/main/%5CDOCUMENTATION.md
correct link : https://github.com/microsoft/powerbi-jupyter/blob/main/DOCUMENTATION.md

Demo Notebook points to : https://github.com/microsoft/powerbi-jupyter/blob/main/\demo\demo.ipynb
Correct link : https://github.com/microsoft/powerbi-jupyter/blob/main/demo/demo.ipynb

Please fix.

**Comment by orshemesh16** [comment]
Thank you for the input, it was fixed in new version (2.0.1).
