### ISSUE TITLE
Error accessing group/report

### ISSUE THREAD

**Issue by jravenel** [microsoft/powerbi-jupyter#18]
Hi, i'm trying to setup powerbi in my jupyter notebook, managed to.  
followed the steps
https://powerbi.microsoft.com/en-us/blog/announcing-power-bi-in-jupyter-notebooks/

but have now this error at the end
('Could not create access token or embed URL: ', Exception('Get embed URL failed with status code ', 401))

What should I do? 
Thanks for your help;

**Comment by pankajigec26** [comment]
Hi jravenel , I have setup at my end by learning through different source of articles  and have documented the steps. Hope this will help [https://mymlspace.com/integrating-power-bi-with-jupyter-notebook/](url)

**Comment by jravenel** [comment]
Hey @pankajigec26, thanks for your message. I cannot access your link though. 
Can you send again?

**Comment by pankajigec26** [comment]
@jravenel i have updated the link, you must be able to access now

**Comment by jravenel** [comment]
thanks @pankajigec26 will let you know.

**Comment by orshemesh16** [comment]
Hi, new version has been released recently(2.0.1) with several breaking changes in the authentication methods that simplify the API. You can see full documentation [here](https://github.com/microsoft/powerbi-jupyter/blob/main/DOCUMENTATION.md). If you still encounter authentication issues, please open new issue.
