### ISSUE TITLE
Export all rows via export_visual_data API

### ISSUE THREAD

**Issue by pdarunraj** [microsoft/powerbi-jupyter#21]
Please provide the options to export all rows from visual data without having to feed number to rows keyword.

export_visual_data(page_name, visual_name, **rows=all_rows**, export_data_type=models.ExportDataType.SUMMARIZED.value)

The [documentation ](https://github.com/microsoft/powerbi-jupyter/blob/main/DOCUMENTATION.md) doesnt explain about it.

**Comment by orshemesh16** [comment]
Thank you for your input, we updated the method to return all rows by default, see new [documentation](https://github.com/microsoft/powerbi-jupyter/blob/main/DOCUMENTATION.md#export_visual_data).
