### ISSUE TITLE
Displaying reports under VS Code with Jupyter extension

### ISSUE THREAD

**Issue by hristochr** [microsoft/powerbi-jupyter#23]
Has anyone successfully been able to display a report under VS Code?

My setup:

- VS code latest with python and jupyter extensions installed 
- python 3.7.
- nodejs 16.4
- starting with a blank conda environment

I successfully get device authentication. When I try to render a report:
![image](https://user-images.githubusercontent.com/22388580/148254401-797a4b76-9a10-4366-bca4-cab03cf0b848.png)
I click on enable, then restart kernel, authenticate again but keep getting the same error.

**Comment by bapat-atharva** [comment]
Hi @hristochr, were you able to make it run in vs code ?

We need to install additional Jupyter extensions to make it run.
Here is what we have - 
![image](https://user-images.githubusercontent.com/60684660/231054414-b3ea09e8-26b8-4323-a958-83358a0eb9d3.png)

Additionally, also have ipykernel installed.
`pip install -U ipykernel`
