### ISSUE TITLE
Render report in Edge vs Chrome

### ISSUE THREAD

**Issue by az-alig** [microsoft/powerbi-jupyter#26]
Rendering a report in Edge doesn't seem to work.

Run notebook in Edge, report won;t render. It is picked up, can see the report object attributes etc.

Same code runs and renders correctly in Chrome.

On rerunning the notebook in Edge the report will render.

Not tried with closing/restarting jupyter.

**Comment by bapat-atharva** [comment]
Hi @az-alig, we tried to reproduce it in Edge, Chrome, Firefox but did not observe your results.

Are you applying any filters/slicers or using any other default parameters ?  Can you please check and let us know if you have any additional information ?

**Comment by may-hartov** [comment]
Unable to reproduce, no repro steps are provided.
