### ISSUE TITLE
powerbiclient installation

### ISSUE THREAD

**Issue by zeinabwalid** [microsoft/powerbi-jupyter#32]
Hello all,
when install powerbiclient package, using this command "pip install powerbiclient" 
this error is shown: 
ERROR: Could not find a version that satisfies the requirement powerbiclient (from versions: none)
ERROR: No matching distribution found for powerbiclient

Best Regards.

**Comment by bapat-atharva** [comment]
Hi @zeinabwalid, what version of python are you using ? Also, can you upgrade the pip version and try installing ?
