### ISSUE TITLE
Unable to move across report tabs in the embedded report

### ISSUE THREAD

**Issue by Cagataydemirkol** [microsoft/powerbi-jupyter#33]
Hi team,

I have a Power BI report with multiple report tabs and the data I want to extract from a table is not on the active page by default. Is there an ability to set the active page to a page with a known page id through coding? I am aware it is possible by manually selecting the tab from the embedded visual but my goal is to eliminate this manual step by writing a code to switch to another page automatically.

**Comment by bapat-atharva** [comment]
Hi @Cagataydemirkol,

Right now, setting active page using code is not supported on jupyter wrapper. We have taken your request in consideration about this feature.

As a workaround, if you always want to open the report with the page from which you want to extract data, you could save your report in app.powerbi.com with that page as active. This will automatically open the embedded report with that page as active.

**Comment by yashgMAQ** [comment]
Hi @bapat-atharva 
till when can we expect the functionality to change the active page using code?
