### ISSUE TITLE
Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': CustomEvent object could not be cloned.

### ISSUE THREAD

**Issue by ciaran28** [microsoft/powerbi-jupyter#35]
PBI_visualize = QuickVisualize(get_dataset_config(df), auth=device_auth)

At the stage I run "PBI_Visualize", it will attempt to display the the visual but then fails with:
"Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': CustomEvent object could not be cloned."

The error occurs in Azure Databricks

**Comment by bapat-atharva** [comment]
Hi @ciaran28,

We tried to run the `QuickVisualize` in ADB notebook and it works as expected for us. Can you provide any additional details that you might be using that could cause the issue ? Does the issue also reproduce on the sample code(and CSV) we have provided ?
