### ISSUE TITLE
Dropdown slicer with single select is not working

### ISSUE THREAD

**Issue by priyanka-art** [microsoft/powerbi-jupyter#36]
when I am trying to use dropdown slicer with single select option it is not able to select and report coming as blank
def filter_report(filter_list1,filter_list2):
    region_filter1 = {
            '$schema': "http://powerbi.com/product/schema#basic",
            'target': {
                'table': "Roadmap_Allviewers",
                'column': "Brand_divided"
            },
            'operator': "In",
            'values': [filter_list1]
        }
    region_filter2 = {
            '$schema': "http://powerbi.com/product/schema#basic",
            'target': {
                'table': "Roadmap_Allviewers",
                'column': "Workstream"
            },
            'operator': "In",
            'values': [filter_list2]
        }
   
    report.remove_filters()
    report.update_filters([region_filter1,region_filter2])

**Comment by bapat-atharva** [comment]
Hi @priyanka-art,

Thank you for reporting the issue. I was able to reproduce it with single-select slicer.
It seems it is not related to this package but the powerbi-client. We will address it as soon as possible.

When you say the report comes to be blank, you still do see the filtered slicer list, right ?

**Comment by ayeshurun** [comment]
The issue is closed since no response was received.

**Comment by ayeshurun** [comment]
The observed behavior is functioning as designed. For additional support, please contact your account manager or the [Fabric Support Team](https://support.fabric.microsoft.com/en-us/support/).
