### ISSUE TITLE
Exception: Power BI report is not embedded

### ISSUE THREAD

**Issue by yashgMAQ** [microsoft/powerbi-jupyter#37]
I try to open the PowerBI report but it gives error 

Exception                                 Traceback (most recent call last)
Cell In[12], line 1
----> 1 pages = report.get_pages()
      2 display(pages)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\powerbiclient\report.py:562, in Report.get_pages(self)
    556 """Returns pages list of the embedded Power BI report
    557 
    558 Returns:
    559     list: list of pages
    560 """
    561 if not self._embedded:
--> 562     raise Exception(self.REPORT_NOT_EMBEDDED_MESSAGE)
    564 # Start getting pages on client side
    565 self._get_pages_request = True

Exception: Power BI report is not embedded

**Comment by bapat-atharva** [comment]
Hi @yashgMAQ, get_pages operation requires the report to be rendered first. Please run `report` on a cell to embed it, and then call the method.
