### ISSUE TITLE
Embed a specified report page or even a single visual

### ISSUE THREAD

**Issue by Ljupch0** [microsoft/powerbi-jupyter#39]
Hi, would it be possible when initializing the report, to preset filters and set it to a given report page? Or would that be accomplished by using a bookmark that takes the user to a certain page?

How about embedding only a specific visual from a given page?

If not possible today, is it in the backlog? Thank you.

**Comment by v-MadhavC** [comment]
To preset filters and set a specific report page, you can configure this directly in Power BI Desktop or Service within the report itself. However, it is not possible to preset filters or set a specific page directly through the embedding process.

**Comment by v-MadhavC** [comment]
It's not supported to preset filters or navigate to a specific report page at load time. If this is a key feature for you, we suggest submitting a vote for it on the [idea portal](https://ideas.fabric.microsoft.com/). For applying filters at runtime, you can utilize the updateFilters method.
