### ISSUE TITLE
extract visual data from report in python script and not in jupyter notebook widget.

### ISSUE THREAD

**Issue by premanand09** [microsoft/powerbi-jupyter#41]
Hi,
I have tried this library to embed report in jupyter notebooks. But I want to extract the data from report visuals in python script and run through commandline. Currently report is getting embedded after calling Report() on jupyter notebooks only. When i try to run the same thing in python script commandline it says report is not embedded.
Could you please suggest me some resource which i can use for reference to extract data from power report  visuals in python .py script.

**Comment by moltra** [comment]
I am getting ready to start using this package to try and pull data, if I can, I will let you know.

**Comment by CrasCris** [comment]
> I am getting ready to start using this package to try and pull data, if I can, I will let you know.

Did you find the way to how to do it ?

**Comment by Mike-Honey** [comment]
I'm facing sort of similar challenges - I've stayed with the notebook but trying to use Run All to work through the rendering and then interacting with reports. But it seems quite flaky in that mode.  Visually I can see there's a lag between the "report" cell that renders the report and the actual report output becoming visible.  So I tried adding a wait at the start of the next cell, but I still often stalls, errors or gives incomplete results.  
Here's my project fwiw - I wrote it to be generic for any report.
https://github.com/Mike-Honey/powerbi-export-all-visuals

**Comment by ayeshurun** [comment]
Thank you for reporting this issue. We're closing GitHub issues on 01/01/2025. For further assistance, we kindly request that you direct your inquiries to the following support channels:

- Bug Reports and Technical Assistance: Visit the [Fabric Developer Community Forum](https://community.fabric.microsoft.com/t5/Developer/bd-p/Developer). Our team and community experts are ready to assist you.
- Additional Support: Contact your account manager or reach out to the [Fabric Support Team](https://support.fabric.microsoft.com/en-us/support/).

Thank you,
The Power BI Embedded Team
