### ISSUE TITLE
Adding to Conda-Forge

### ISSUE THREAD

**Issue by moltra** [microsoft/powerbi-jupyter#42]
I would like to know if it would be possible to get this added to Conda-Forge.  I am willing to do the work to do it, if it is allowed.  I will have to learn how first, but it is something that I have been wanting to learn.

**Comment by rxm7706** [comment]
Hi I was looking to use conda-forge too  - to install and use powerbiclient, the first thing we would need is a source distribution at https://pypi.org/project/powerbiclient/3.1.1/#files - which is currently missing. 

@orshemesh16 @KotanaSai21 is that some that can be done.. to enable conda users. I can help with the conda-forge feedstock and recipe if needed.

**Comment by rxm7706** [comment]
Add here
https://ideas.fabric.microsoft.com/ideas/idea/?ideaid=2fc7ca31-88a2-ef11-95f6-000d3a7a93ec
