### ISSUE TITLE
Report does not render in Microsoft Fabric Notebook

### ISSUE THREAD

**Issue by jpierzchala** [microsoft/powerbi-jupyter#43]
Hi

I am trying to use powerbi-jupyter client in Microsoft Fabric Notebook (which are feature identical to Synapse Notebooks if I'm not mistaken).

I use following code:
```
# Setup for getting data from PowerBI
from powerbiclient import Report, models, authentication

# Authenticate to Power BI service using InteractiveLoginAuthentication
auth = authentication.DeviceCodeLoginAuthentication()

# Configure view mode
view_mode=models.EmbedMode.VIEW.value

# NewSales Report configuration
group_id = "GROUP-GUID"
report_id = "REPORT-GUID"

# Create a Power BI report object
report = Report(group_id=group_id, report_id=report_id, auth=auth)
report
```

The report does not render.

Any idea what can be done to make this work in Microsoft Fabric?

**Comment by KotanaSai21** [comment]
@jpierzchala , 

For supporting Fabric Notebook, we added a support to Pyspark data frames in this [PR](https://github.com/microsoft/powerbi-jupyter/commit/b0a2145b7558e7ad8e3f85ecb727e04e8633b79d).

Please install the latest version `3.1.1` and let us know if the issue still exists.
