### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by sagazluiz** [microsoft/powerbi-jupyter#45]
Enviroment: 
Python 3.10.11 (main, May 15 2023, 19:29:30) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

pandas                   2.0.2

Function: 
# Create a Power BI report from your data
PBI_visualize = QuickVisualize(get_dataset_config(df_pbi_), auth=interactive_auth) # auth=device_auth

# Render the new report
PBI_visualize

Error: 
AttributeError: 'DataFrame' object has no attribute 'dtype'

**Comment by KotanaSai21** [comment]
@sagazluiz , 

It's a generic error message to investigate the possible reason. Plese check the [Considerations and Limitations](https://github.com/microsoft/powerbi-jupyter/blob/main/DOCUMENTATION.md#considerations-and-limitations) for the data frame passing to the function.

If the issue still exists, please provide more information.
