### ISSUE TITLE
Failed to load model class 'QuickVisualizeModel' from module 'powerbi-jupyter-client' 

### ISSUE THREAD

**Issue by ChrisPy-RuBy** [microsoft/powerbi-jupyter#46]
Hello, 

I'm currently trying to follow your demos for you powerbi widgets for jupyter. 
Specifically I am running the Visualize with Power BI demo.ipynb. 

I have followed the instructions for jupyter lab but if I attempt to run the following
code 

```python 
# Create a Power BI report from your data
PBI_visualize = QuickVisualize(get_dataset_config(df), auth=device_auth)
PBI_visualize
```
I get the following error
```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'QuickVisualizeModel' from module 'powerbi-jupyter-client'
loadClass@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1:74936
loadModelClass@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:10729
_make_model@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:7517
new_model@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:5137
handle_comm_open@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:3894
134/v/this._handleCommOpen@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1:73473
_handleCommOpen@http://localhost:8888/static/lab/jlab_core.c2628bfc928bd194fa79.js?v=c2628bfc928bd194fa79:1:1240940
```

Following the instructionsn and inspecting the browser debugger gives
<img width="1470" alt="image" src="https://github.com/microsoft/powerbi-jupyter/assets/25936040/806c4cb1-f310-4c59-8504-894806835c76">

I am running the notebook via jupyter lab within a poetry environment. 
The poetry.lock file is attached. 
[lock.txt](https://github.com/microsoft/powerbi-jupyter/files/13505482/lock.txt)

Any help would be appreciated.

**Comment by MoonforYoung** [comment]
The same error occurred to me, keep tracking.

**Comment by KotanaSai21** [comment]
We were able to reproduce the issue while embedding report within a poetry environment. 

Please check this [comment](https://github.com/microsoft/powerbi-jupyter/issues/47#issuecomment-2006859209). We followed the steps mentioned and we were able to embed report within a poetry environment.

**Comment by ChrisPy-RuBy** [comment]
Thanks will give that ago
