### ISSUE TITLE
Recover the value of a visual 

### ISSUE THREAD

**Issue by adama-hawa** [microsoft/powerbi-jupyter#49]
Hello,

Have you ever managed to recover the value of a visual please?

**Comment by adama-hawa** [comment]
Sorry, i use export_visual_data for this

**Comment by KotanaSai21** [comment]
@adama-hawa, is this issue still relevant and do you need any help here?

**Comment by adama-hawa** [comment]
Yes, I'm having a bit of trouble filtering and displaying a visual of a report. I've written a code to complement yours but it doesn't work at the moment. If you've already done one, I'd like to use it as inspiration if possible.

**Comment by v-MadhavC** [comment]
To retrieve a list of all visuals on a specific page of your report:
```
visuals_on_page = report.visuals_on_page('Enter the name of the embedded report page here')
print(visuals_on_page)
```

To display the visual data of the report:
```
visual_data = report.export_visual_data(page_name, visual_name)
print("Visual Data: ", visual_data)
```

For more details, refer to the documentation:
[powerbi-jupyter/DOCUMENTATION.md at main · microsoft/powerbi-jupyter (github.com)](https://github.com/microsoft/powerbi-jupyter/blob/main/DOCUMENTATION.md#visuals_on_page)

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed.
