### ISSUE TITLE
Set Active page call not working

### ISSUE THREAD

**Issue by MandlaSibandaHI** [microsoft/powerbi-jupyter#50]
the set_active_page(page_name) does not work. is there a way a different way to change the active page?

**Comment by KotanaSai21** [comment]
It's working fine for us. 

Get the page name from the function `get_pages()` and set the active page using `set_active_page(page_name)`. Followed the below code.

```
report.get_pages()
report.set_active_page("ReportSection1234")
report
```

Please provide more additional information if the issue still exists.
