### ISSUE TITLE
error displaying widget model not found

### ISSUE THREAD

**Issue by lalitsingh24x7** [microsoft/powerbi-jupyter#51]
Getting error while running the bellow code and am also running the Jupiter lab in the container, so for that please also check the Dockerfile.

Tried many combination but none of the solution worked.

## Code:
from powerbiclient import Report, models
from powerbiclient.authentication import DeviceCodeLoginAuthentication

device_auth = DeviceCodeLoginAuthentication()
group_id="Workspace ID"
report_id="Report ID"
report = Report(group_id=group_id, report_id=report_id, auth=device_auth)
report

## Error:
error displaying widget model not found 

## Dockerfile:
FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

RUN microdnf update -y && \
    microdnf install -y python38 wget tar gzip zip unzip git gcc-c++.x86_64 python38-devel python38-setuptools && \
    microdnf clean all

RUN dnf module -y install nodejs:18

WORKDIR /

RUN pip3 install ipympl matplotlib jupyterlab virtualenv powerbiclient ipywidgets ipympl

RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager && \
    jupyter labextension install jupyter-matplotlib && \
    jupyter labextension update --all && \
    jupyter lab build

RUN mkdir -p /users/home /jupyter/kernels && \
    chmod -R 755 /users /jupyter

EXPOSE 8880 8866

CMD ["jupyter", "lab", "--notebook-dir=/users", "--allow-root", "--port=8866", "--ip=0.0.0.0"]

**Comment by KotanaSai21** [comment]
@lalitsingh24x7 , 

We found that the issue is not related to our package, rather the package manager Conda.

Please try the steps mentioned in these GitHub Issues https://github.com/microsoft/powerbi-jupyter/issues/47#issuecomment-2006859209,  https://github.com/microsoft/powerbi-jupyter/issues/19#issuecomment-1514219377.

**Comment by lalitsingh24x7** [comment]
Hi @KotanaSai21 

Thanks for the suggestion , it's working after bellow modification.


FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

RUN microdnf update -y &&
microdnf install -y python38 wget tar gzip zip unzip git gcc-c++.x86_64 python38-devel python38-setuptools &&
microdnf clean all

RUN dnf module -y install nodejs:18

WORKDIR /

RUN pip3 install matplotlib jupyterlab virtualenv ipywidgets ipympl

RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager && \
    jupyter labextension install jupyter-matplotlib && \
    jupyter labextension update --all &&
    jupyter lab build

**RUN pip3 install powerbiclient
RUN jupyter lab build**

RUN mkdir -p /users/home /jupyter/kernels &&
chmod -R 755 /users /jupyter

EXPOSE 8880 8866

CMD ["jupyter", "lab", "--notebook-dir=/users", "--allow-root", "--port=8866", "--ip=0.0.0.0"]
