### ISSUE TITLE
Authenticacion with msal.ConfidentialClientApplication()

### ISSUE THREAD

**Issue by CrasCris** [microsoft/powerbi-jupyter#53]
Why if i get the access_token using microsoft graph application it fail to load the report ?, is it possible to authentication only for and app and not using human interaction ?

**Comment by v-MadhavC** [comment]
It looks like you tried using a Graph access token, but you actually need a Power BI access token. We provide two ways to get the correct access token. Refer the following documentation for more details: [Home · microsoft/powerbi-jupyter Wiki (github.com)](https://github.com/microsoft/powerbi-jupyter/wiki#authenticate-to-power-bi-and-acquire-an-access-token).

If you prefer, you can also create your own logic to get a Power BI AAD token and provide that token when creating the Report object. For more information, refer - [Permission tokens needed to embed a Power BI app - Power BI | Microsoft Learn](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-tokens?tabs=embed-for-your-organization). But please keep in mind that we use the "embed for your organization" scenario in this library.

**Comment by CrasCris** [comment]
I use the same logic powerbi rest api docs

**Comment by v-MadhavC** [comment]
Could you please provide the specific documentation or resource you are referring to regarding the Power BI embed token scenario? 
Also, here are some relevant documentations that you can follow - [Generate an embed token in Power BI embedded analytics - Power BI | Microsoft Learn](https://learn.microsoft.com/en-us/power-bi/developer/embedded/generate-embed-token), [Embed Token - Generate Token - REST API (Power BI Power BI REST APIs) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/power-bi/embed-token/generate-token)

If you tried to use the embed token scenario (App owns data/embed for your customers), it's important to note that this is not supported for the powerbi-jupyter.

**Comment by CrasCris** [comment]
Yep, i mean just to another form to authentication, like the api rest
