### ISSUE TITLE
what are the event handlers for? how should we use them

### ISSUE THREAD

**Issue by Mike-Honey** [microsoft/powerbi-jupyter#55]
I have a working notebook based on your sample, so thanks for getting me started.
https://github.com/Mike-Honey/powerbi-export-all-visuals

But I don't understand what the "event handlers" are for? How should we use them?  Is there any documentation or examples of this?

All I've figured out so far is that they seem essential - when I removed them from my code, the report object stopped responding.

**Comment by v-MadhavC** [comment]
Event handlers in Power BI are essential for enabling communication between an embedded component (such as a report, dashboard) and your web application. 

When something happens inside the embedded component—like a user interaction or an automated event, such as a visual being rendered—an event is triggered. Event handlers allow you to capture these events and define how your application should respond. 

You can set up event handlers to listen for specific actions, like when a report button is clicked (buttonClicked),  a data point is selected (dataSelected), a page is changed (pageChanged), or the report is fully rendered (rendered). 

Refer to this documentation for more details and let us know if you have any further queries.
[How to handle events in a Power BI embedded analytics application | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/handle-events)

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed.
