### ISSUE TITLE
Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': CustomEvent object could not be cloned.

### ISSUE THREAD

**Issue by genloz** [microsoft/powerbi-jupyter#56]
Hi Team! Just wondering if you have any thoughts on this challenge. 

My customer has followed the tutorial here: https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/powerbi-jupyter and they are seeing an error when they embed the report, though once the screen is refreshes it embeds successfully (Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': CustomEvent object could not be cloned)
 
They are injecting javascript to refresh the screen, but once the screen is refreshed and the report is embedded when they invoke any of the functions  report.get_pages(), report.visuals_on_page(pagename) or report.export_visual_data(page_name, visual_name) it does not return any result and function continues to run for long time. They need to manually interrupt the execution and rerun again to get the results. These functions are not returning the results consistently.

Advice appreciated, thank you!

**Comment by v-MadhavC** [comment]
We have tried using the functions, but we did not encounter any such error. The functions executed as expected, returning results without any delays.

Could you provide the specific code you're using to embed the Power BI report and invoke these functions? Also, does the issue reproduce on the sample code provided in the demo?

**Comment by genloz** [comment]
Please see embed code below
![image (3)](https://github.com/user-attachments/assets/1ecea2c7-4b73-40f0-ac30-08167b075332)

**Comment by genloz** [comment]
@v-MadhavC I've had a few people mention to me that they're facing the same issue just FYI

**Comment by v-MadhavC** [comment]
It seems like you are setting the access token using the set_access_token() method after initializing the report object. Could you please clarify how you are generating the access token?
![image](https://github.com/user-attachments/assets/7e7f887f-aea5-48cd-8e6f-b8fd3fd7b063)

**Comment by ayeshurun** [comment]
We haven't received any feedback for a while. 

Please continue to share your feedback and get support through these channels:

- For Bug Reports and Technical Assistance: Visit the [Fabric Developer Community Forum](https://community.fabric.microsoft.com/t5/Developer/bd-p/Developer). Our team and community experts are ready to assist you.
- For Additional Support: Contact your account manager or reach out to the [Fabric Support Team](https://support.fabric.microsoft.com/en-us/support/).

Thank you,
The Power BI Embedded Team
