### ISSUE TITLE
Resizing the embedded report

### ISSUE THREAD

**Issue by pawarbi** [microsoft/powerbi-jupyter#9]
Great work on this, thank you so much! 

How do I resize the embedded dashboard in Jupyter notebook? I did not see any arguments to specify the width and height. Can you please point to it if it exists, if not that would be a feature request. Thanks!

**Comment by orshemesh16** [comment]
Hi, you can use the method set_size, see documentation: [Set width and height of the report container in pixels](https://github.com/microsoft/powerbi-jupyter/blob/main/DOCUMENTATION.md#set_size)
